stages:
  - build

# dist-build:
#   image: node:latest
#   stage: build
#   script:
#     - npm install
#     - npm run build

docker-build:
  image: node:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - npm install
    - npm run build
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  
  
# pages:
#   image: node:latest
#   stage: deploy
#   script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - mv dist public
#   artifacts:
#     paths:
#     - public
#   only:
#   - main
