stages:
  - build
  - deploy

dist-build:
  image: node:latest
  stage: build
  stage: 
    - docker:latest
    - docker:dind
  script:
    - npm install
    - npm run build
    - docker images
    - cd dist
    - ls


docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker run -p 8081:80 "$CI_REGISTRY_IMAGE"
  

# deploy-container:
#   image: registry.gitlab.com/damorz/book_shelf:latest
#   stage: deploy
#   script:
#     - cd src
#     - ls
    

# pages:
#   image: node:latest
#   stage: deploy
#   script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - mv dist public
#   artifacts:
#     paths:
#     - public
#   only:
#   - main
