
# stages:
#   - build

# dist-build:
#   image: node:latest
#   stage: build
#   script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - mv dist public

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/damorz/book_shelf .
    - docker push registry.gitlab.com/damorz/book_shelf
  

# deploy-container:
#   image: registry.gitlab.com/damorz/book_shelf:latest
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - main
    
    
    
# pages:
#   image: node:latest
#   stage: deploy
#   script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - mv dist public
#   artifacts:
#     paths:
#     - public
#   only:
#   - main



